/*Procedura che permette di aggiornare la quantità dei mobili disponibili*/

CREATE OR REPLACE PROCEDURE AGGIORNA_QUANTITA (ID_CONTRATTO NUMBER)
IS

CURSOR MOBILI_IN_CONTRATTO IS SELECT DISTINCT COD_BARRA_M,QUANTITA_AQUISTATA FROM CONTRATTO_MOBILE
		WHERE ID_CONT=ID_CONTRATTO;
TEMP_MOBILE_CONTRATTO MOBILI_IN_CONTRATTO%ROWTYPE;

BEGIN
OPEN MOBILI_IN_CONTRATTO;
FETCH MOBILI_IN_CONTRATTO INTO TEMP_MOBILE_CONTRATTO;
WHILE MOBILI_IN_CONTRATTO%FOUND LOOP
UPDATE MOBILE SET QUANTITA_M=QUANTITA_M-TEMP_MOBILE_CONTRATTO.QUANTITA_AQUISTATA WHERE COD_BARRA_M=TEMP_MOBILE_CONTRATTO.COD_BARRA_M;
FETCH MOBILI_IN_CONTRATTO INTO TEMP_MOBILE_CONTRATTO;
END LOOP;
CLOSE MOBILI_IN_CONTRATTO;

END;
/
