/*Procedura che permette di aggiornare il prestigio di un VENDITORE*/


CREATE OR REPLACE PROCEDURE AGGIORNA_PRESTIGIO (TESSERA_VENDITORE CHAR)
IS

DECLARE
CONTA NUMBER;


BEGIN
SELECT COUNT(*) INTO CONTA FROM CONTRATTO WHERE #TESSERA=:TESSERA_VENDITORE;
IF CONTA<10 THEN
UPDATE VENDITORE SET ID_PRESTIGIO=01 WHERE #TESSERA=TESSERA_VENDITORE;
ELSE IF CONTA<50
UPDATE VENDITORE SET ID_PRESTIGIO=02 WHERE #TESSERA=TESSERA_VENDITORE;
ELSE IF CONTA<100
UPDATE VENDITORE SET ID_PRESTIGIO=03 WHERE #TESSERA=TESSERA_VENDITORE;
ELSE
UPDATE VENDITORE SET ID_PRESTIGIO=04 WHERE #TESSERA=TESSERA_VENDITORE;
END IF;
END IF;
END IF;

END;
/
