/*Procedura che permette di concludere un CONTRATTO registrando il pagamento, aggiornando la quantità dei mobili disponibili e il prestigio del venditore*/

CREATE OR REPLACE PROCEDURE INSERIMENTO_CONTRATTO (ID_CONTRATTO NUMBER,MODALITA_PAGAMENTO CHAR)
IS

DECLARE
TOTALE NUMBER;
MAX NUMBER
TESSERA_VENDITORE CHAR;

BEGIN
AGGIORNA_QUANTITA(ID_CONTRATTO);   /*Richiama l'altra procedura*/

SELECT SUM(PREZZO_SCONTATO*QUANTITA_AQUISTATA) INTO TOTALE
FROM CONTRATTO_MOBILE NATURAL JOIN MOBILE
WHERE ID_CONT=:ID_CONTRATTO;

UPDATE CONTRATTO SET TOTALE_PAGAMENTO=TOTALE WHERE ID_CONT=ID_CONTRATTO;

SELECT MAX(ID_P) INTO MAX
FROM PAGAMENTO;

INSERT INTO PAGAMENTO VALUES (MAX+1,MODALITA_PAGAMENTO,sysdate,(SELECT CF_CL FROM CONTRATTO WHERE ID_CONT=:ID_CONTRATTO),ID_CONTRATTO);

SELECT #TESSERA INTO TESSERA_VENDITORE FROM CONTRATTO WHERE ID_CONT=:ID_CONTRATTO;
AGGIORNA_PRESTIGIO(TESSERA_VENDITORE);  /*Richiama l'altra procedura*/

END;
/
