/*Procedura che conta quante mensilità(buste paga) ha ricevuto un dipendente*/

CREATE OR REPLACE PROCEDURE QUANTITA_BUSTEPAGA (TESSERA_VENDITORE CHAR) RETURN NUMBER
IS

DECLARE
CONTA NUMBER;

BEGIN
SELECT COUNT(*) INTO CONTA FROM BUSTA_PAGA WHERE #TESSERA=:TESSERA_VENDITORE;

RETURN CONTA
END;
/
