/*Procedura che ritorna il totale pagamenti dell'ultimo mese */


CREATE OR REPLACE PROCEDURE TOTALE_PAGAMENTI() RETURN NUMBER
IS

DECLARE
TOTALE NUMBER;

BEGIN
SELECT SUM(TOTALE_PAGAMENTO) INTO TOTALE FROM PAGAMENTO NATURAL JOIN CONTRATTO WHERE DATA_P<sysdate AND DATA_P>sysdate-30;

RETURN TOTALE

END;
/
