--5. Trigger che impedisce di inserire la data consegna prima della data del contratto
CREATE OR REPLACE TRIGGER DATA_CONSEGNA
BEFORE INSERT ON CONSEGNA
FOR EACH ROW

DECLARE
ERRORE EXCEPTION;

BEGIN
IF DATEDIFF(:NEW.DATA_CONSEGNA , DATA_CONTRATTO)<10 THEN
	RAISE ERRORE;
END IF;


EXCEPTION
WHEN ERRORE THEN
RAISE_APPLICATION_ERROR(-20010,'IMPOSSIBILE INSERIRE QUESTA DATA');

END;