--6. Trigger che impedisce che la data fine sia minore dalla data inizio
CREATE OR REPLACE TRIGGER DATE_ESATTE
BEFORE INSERT ON MOBILE
FOR EACH ROW	--per ogni riga deve essere fatto il controllo

DECLARE
DATE_ERROR EXCEPTION;
D_C DATE;

BEGIN
SELECT DATA_INIZIO INTO D_C
FROM MOBILE NATURAL JOIN PROMOZIONE
IF(:NEW.DATA_FINE < D_C) THEN
	RAISE DATE_ERROR;
END IF;

DECLARE
DATE_ERROR EXCEPTION;

EXCEPTION
WHEN DATE_ERROR THEN
	RAISE_APPLICATION_ERROR(-20003, 'DATA_FINE MINORE DELLA DATA_INIZIO')
END