--4. Trigger che non permette a un montatore di essere un venditore
CREATE OR REPLACE TRIGGER MONTATORE_NOT_VENDITORE
BEFORE INSERT ON MONTATORE
FOR EACH ROW

DECLARE
CURSOR C1 IS SELECT #TESSERA FROM VENDITORE;
TEMP_C1 CHAR(10);

--ECCEZIONI
ERRORE_DOPPIA_ATTIVITA EXCEPTION;

BEGIN
OPEN C1;
FETCH C1 INTO TEMP_C1;
WHILE C1%FOUND LOOP
IF (:NEW.#TESSERA=TEMP_C1) THEN
	RAISE ERRORE_DOPPIA_ATTIVITA;
END IF;
FETCH C1 INTO TEMP_C1;
END LOOP;
CLOSE C1;

EXCEPTION
WHEN ERRORE_DOPPIA_ATTIVITA THEN
RAISE_APPLICATION_ERROR(-20010,'IL DIPENDENTE NON PUO AVERE DOPPIA ATTIVITA');

END;